// QuizMode — 3-question multiple-choice quiz generated by the Quiz Agent.
import { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';

const SCORE_MESSAGES = {
  3: { text: 'Perfect score! You\'re a genius! 🏆', color: '#FFD700' },
  2: { text: 'Great job! Almost perfect! ⭐', color: '#00D4FF' },
  1: { text: 'Good try! Practice makes perfect! 💪', color: '#6C63FF' },
  0: { text: 'Don\'t give up — you\'re learning! 🌟', color: '#00FF88' },
};

const QuizMode = ({ subject, ageLevel, onDone, playSound }) => {
  const [questions, setQuestions] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);
  const [current, setCurrent] = useState(0);
  const [selected, setSelected] = useState(null); // selected option letter
  const [score, setScore] = useState(0);
  const [finished, setFinished] = useState(false);

  useEffect(() => {
    fetch(`${import.meta.env.VITE_API_URL}/api/agents/quiz`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ subject, ageLevel }),
    })
      .then((r) => { if (!r.ok) throw new Error(); return r.json(); })
      .then((data) => { setQuestions(data.questions); setLoading(false); })
      .catch(() => { setError(true); setLoading(false); });
  }, [subject, ageLevel]);

  const handleAnswer = (letter) => {
    if (selected) return; // already answered
    setSelected(letter);
    const correct = letter === questions[current].answer;
    if (correct) {
      setScore((s) => s + 1);
      playSound?.('correct');
    }
  };

  const handleNext = () => {
    if (current + 1 >= questions.length) {
      setFinished(true);
      playSound?.('levelUp');
    } else {
      setCurrent((c) => c + 1);
      setSelected(null);
    }
  };

  const q = questions[current];
  const scoreMsg = SCORE_MESSAGES[score] ?? SCORE_MESSAGES[0];

  if (loading) return (
    <div className="flex-1 flex flex-col items-center justify-center gap-4 p-8">
      <motion.div className="text-5xl" animate={{ rotate: 360 }} transition={{ duration: 1.5, repeat: Infinity, ease: 'linear' }}>⚙️</motion.div>
      <p className="text-[#9CA3AF] font-bold">Generating your quiz…</p>
    </div>
  );

  if (error) return (
    <div className="flex-1 flex flex-col items-center justify-center gap-4 p-8 text-center">
      <p className="text-4xl">😅</p>
      <p className="text-white font-bold">Couldn't load the quiz right now.</p>
      <button onClick={onDone} className="text-[#00D4FF] font-bold">← Go back</button>
    </div>
  );

  if (finished) return (
    <motion.div
      className="flex-1 flex flex-col items-center justify-center gap-6 p-8 text-center"
      initial={{ opacity: 0, scale: 0.9 }}
      animate={{ opacity: 1, scale: 1 }}
    >
      <div className="text-7xl">🎉</div>
      <div>
        <p className="text-5xl font-black text-white mb-2">{score}/{questions.length}</p>
        <p className="font-black text-xl" style={{ color: scoreMsg.color }}>{scoreMsg.text}</p>
      </div>
      <motion.button
        onClick={onDone}
        className="px-8 py-4 rounded-2xl font-black text-white text-lg mt-4"
        style={{ background: 'linear-gradient(135deg, #6C63FF, #00D4FF)' }}
        whileHover={{ scale: 1.05 }}
        whileTap={{ scale: 0.95 }}
      >
        Keep Learning! 🚀
      </motion.button>
    </motion.div>
  );

  return (
    <div className="flex-1 flex flex-col p-6 max-w-xl mx-auto w-full gap-5">
      {/* Progress */}
      <div className="flex items-center gap-3">
        <button onClick={onDone} className="text-[#00D4FF] font-bold text-sm">← Back</button>
        <div className="flex-1 h-2 rounded-full bg-white/10 overflow-hidden">
          <div
            className="h-full rounded-full transition-all"
            style={{ width: `${((current + 1) / questions.length) * 100}%`, background: 'linear-gradient(90deg,#6C63FF,#00D4FF)' }}
          />
        </div>
        <span className="text-[#9CA3AF] text-sm font-bold">{current + 1}/{questions.length}</span>
      </div>

      {/* Question */}
      <AnimatePresence mode="wait">
        <motion.div
          key={current}
          initial={{ opacity: 0, x: 40 }}
          animate={{ opacity: 1, x: 0 }}
          exit={{ opacity: 0, x: -40 }}
          className="flex flex-col gap-4"
        >
          <div className="rounded-2xl p-5" style={{ background: 'rgba(255,255,255,0.05)', border: '1px solid rgba(255,255,255,0.1)' }}>
            <p className="text-[#9CA3AF] text-xs font-bold uppercase mb-2">Question {current + 1}</p>
            <p className="text-white font-bold text-base leading-relaxed">{q.question}</p>
          </div>

          {/* Options */}
          <div className="flex flex-col gap-3">
            {q.options.map((opt) => {
              const letter = opt[0]; // 'A', 'B', 'C', 'D'
              const isCorrect = letter === q.answer;
              const isSelected = letter === selected;
              let border = '1px solid rgba(255,255,255,0.1)';
              let bg = 'rgba(255,255,255,0.04)';
              if (selected) {
                if (isCorrect) { border = '2px solid #00FF88'; bg = 'rgba(0,255,136,0.12)'; }
                else if (isSelected) { border = '2px solid #FF6B6B'; bg = 'rgba(255,107,107,0.12)'; }
              }
              return (
                <motion.button
                  key={opt}
                  onClick={() => handleAnswer(letter)}
                  disabled={!!selected}
                  className="text-left px-5 py-4 rounded-xl font-bold text-white transition-all disabled:cursor-default"
                  style={{ background: bg, border }}
                  whileHover={!selected ? { scale: 1.02 } : {}}
                  whileTap={!selected ? { scale: 0.98 } : {}}
                >
                  {opt}
                  {selected && isCorrect && <span className="ml-2">✅</span>}
                  {selected && isSelected && !isCorrect && <span className="ml-2">❌</span>}
                </motion.button>
              );
            })}
          </div>

          {/* Explanation + Next */}
          {selected && (
            <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="flex flex-col gap-3">
              <div className="rounded-xl px-4 py-3" style={{ background: 'rgba(108,99,255,0.15)', border: '1px solid rgba(108,99,255,0.3)' }}>
                <p className="text-[#9CA3AF] text-sm">💡 {q.explanation}</p>
              </div>
              <motion.button
                onClick={handleNext}
                className="py-4 rounded-xl font-black text-white"
                style={{ background: 'linear-gradient(135deg, #6C63FF, #00D4FF)' }}
                whileHover={{ scale: 1.03 }}
                whileTap={{ scale: 0.97 }}
              >
                {current + 1 < questions.length ? 'Next Question →' : 'See My Score 🏆'}
              </motion.button>
            </motion.div>
          )}
        </motion.div>
      </AnimatePresence>
    </div>
  );
};

export default QuizMode;
